// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RequestBody.proto

package com.sdp.self_rpc_done.protoEntity;

public final class request {
  private request() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestBodyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestBody)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string requestId = 1;</code>
     */
    String getRequestId();
    /**
     * <code>string requestId = 1;</code>
     */
    com.google.protobuf.ByteString
        getRequestIdBytes();

    /**
     * <code>string type = 2;</code>
     */
    String getType();
    /**
     * <code>string type = 2;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>.SelfReq req = 3;</code>
     */
    boolean hasReq();
    /**
     * <code>.SelfReq req = 3;</code>
     */
    request.SelfReq getReq();
    /**
     * <code>.SelfReq req = 3;</code>
     */
    request.SelfReqOrBuilder getReqOrBuilder();
  }
  /**
   * Protobuf type {@code RequestBody}
   */
  public  static final class RequestBody extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RequestBody)
      RequestBodyOrBuilder {
    // Use RequestBody.newBuilder() to construct.
    private RequestBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestBody() {
      requestId_ = "";
      type_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RequestBody(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              requestId_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 26: {
              request.SelfReq.Builder subBuilder = null;
              if (req_ != null) {
                subBuilder = req_.toBuilder();
              }
              req_ = input.readMessage(request.SelfReq.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(req_);
                req_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return request.internal_static_RequestBody_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return request.internal_static_RequestBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              request.RequestBody.class, request.RequestBody.Builder.class);
    }

    public static final int REQUESTID_FIELD_NUMBER = 1;
    private volatile Object requestId_;
    /**
     * <code>string requestId = 1;</code>
     */
    public String getRequestId() {
      Object ref = requestId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      }
    }
    /**
     * <code>string requestId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      Object ref = requestId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private volatile Object type_;
    /**
     * <code>string type = 2;</code>
     */
    public String getType() {
      Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQ_FIELD_NUMBER = 3;
    private request.SelfReq req_;
    /**
     * <code>.SelfReq req = 3;</code>
     */
    public boolean hasReq() {
      return req_ != null;
    }
    /**
     * <code>.SelfReq req = 3;</code>
     */
    public request.SelfReq getReq() {
      return req_ == null ? request.SelfReq.getDefaultInstance() : req_;
    }
    /**
     * <code>.SelfReq req = 3;</code>
     */
    public request.SelfReqOrBuilder getReqOrBuilder() {
      return getReq();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRequestIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestId_);
      }
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
      }
      if (req_ != null) {
        output.writeMessage(3, getReq());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRequestIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestId_);
      }
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
      }
      if (req_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getReq());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof request.RequestBody)) {
        return super.equals(obj);
      }
      request.RequestBody other = (request.RequestBody) obj;

      boolean result = true;
      result = result && getRequestId()
          .equals(other.getRequestId());
      result = result && getType()
          .equals(other.getType());
      result = result && (hasReq() == other.hasReq());
      if (hasReq()) {
        result = result && getReq()
            .equals(other.getReq());
      }
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestId().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      if (hasReq()) {
        hash = (37 * hash) + REQ_FIELD_NUMBER;
        hash = (53 * hash) + getReq().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static request.RequestBody parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static request.RequestBody parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static request.RequestBody parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static request.RequestBody parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static request.RequestBody parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static request.RequestBody parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static request.RequestBody parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static request.RequestBody parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static request.RequestBody parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static request.RequestBody parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static request.RequestBody parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static request.RequestBody parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(request.RequestBody prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestBody}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestBody)
        request.RequestBodyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return request.internal_static_RequestBody_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return request.internal_static_RequestBody_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                request.RequestBody.class, request.RequestBody.Builder.class);
      }

      // Construct using com.sdp.protoEntity.request.RequestBody.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        requestId_ = "";

        type_ = "";

        if (reqBuilder_ == null) {
          req_ = null;
        } else {
          req_ = null;
          reqBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return request.internal_static_RequestBody_descriptor;
      }

      public request.RequestBody getDefaultInstanceForType() {
        return request.RequestBody.getDefaultInstance();
      }

      public request.RequestBody build() {
        request.RequestBody result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public request.RequestBody buildPartial() {
        request.RequestBody result = new request.RequestBody(this);
        result.requestId_ = requestId_;
        result.type_ = type_;
        if (reqBuilder_ == null) {
          result.req_ = req_;
        } else {
          result.req_ = reqBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof request.RequestBody) {
          return mergeFrom((request.RequestBody)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(request.RequestBody other) {
        if (other == request.RequestBody.getDefaultInstance()) return this;
        if (!other.getRequestId().isEmpty()) {
          requestId_ = other.requestId_;
          onChanged();
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (other.hasReq()) {
          mergeReq(other.getReq());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        request.RequestBody parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (request.RequestBody) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object requestId_ = "";
      /**
       * <code>string requestId = 1;</code>
       */
      public String getRequestId() {
        Object ref = requestId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          requestId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string requestId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRequestIdBytes() {
        Object ref = requestId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          requestId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string requestId = 1;</code>
       */
      public Builder setRequestId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string requestId = 1;</code>
       */
      public Builder clearRequestId() {

        requestId_ = getDefaultInstance().getRequestId();
        onChanged();
        return this;
      }
      /**
       * <code>string requestId = 1;</code>
       */
      public Builder setRequestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        requestId_ = value;
        onChanged();
        return this;
      }

      private Object type_ = "";
      /**
       * <code>string type = 2;</code>
       */
      public String getType() {
        Object ref = type_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 2;</code>
       */
      public Builder setType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 2;</code>
       */
      public Builder clearType() {

        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>string type = 2;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        type_ = value;
        onChanged();
        return this;
      }

      private request.SelfReq req_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          SelfReq, SelfReq.Builder, SelfReqOrBuilder> reqBuilder_;
      /**
       * <code>.SelfReq req = 3;</code>
       */
      public boolean hasReq() {
        return reqBuilder_ != null || req_ != null;
      }
      /**
       * <code>.SelfReq req = 3;</code>
       */
      public request.SelfReq getReq() {
        if (reqBuilder_ == null) {
          return req_ == null ? request.SelfReq.getDefaultInstance() : req_;
        } else {
          return reqBuilder_.getMessage();
        }
      }
      /**
       * <code>.SelfReq req = 3;</code>
       */
      public Builder setReq(request.SelfReq value) {
        if (reqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          req_ = value;
          onChanged();
        } else {
          reqBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.SelfReq req = 3;</code>
       */
      public Builder setReq(
          request.SelfReq.Builder builderForValue) {
        if (reqBuilder_ == null) {
          req_ = builderForValue.build();
          onChanged();
        } else {
          reqBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.SelfReq req = 3;</code>
       */
      public Builder mergeReq(request.SelfReq value) {
        if (reqBuilder_ == null) {
          if (req_ != null) {
            req_ =
              request.SelfReq.newBuilder(req_).mergeFrom(value).buildPartial();
          } else {
            req_ = value;
          }
          onChanged();
        } else {
          reqBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.SelfReq req = 3;</code>
       */
      public Builder clearReq() {
        if (reqBuilder_ == null) {
          req_ = null;
          onChanged();
        } else {
          req_ = null;
          reqBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.SelfReq req = 3;</code>
       */
      public request.SelfReq.Builder getReqBuilder() {

        onChanged();
        return getReqFieldBuilder().getBuilder();
      }
      /**
       * <code>.SelfReq req = 3;</code>
       */
      public request.SelfReqOrBuilder getReqOrBuilder() {
        if (reqBuilder_ != null) {
          return reqBuilder_.getMessageOrBuilder();
        } else {
          return req_ == null ?
              request.SelfReq.getDefaultInstance() : req_;
        }
      }
      /**
       * <code>.SelfReq req = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          SelfReq, SelfReq.Builder, SelfReqOrBuilder>
          getReqFieldBuilder() {
        if (reqBuilder_ == null) {
          reqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              SelfReq, SelfReq.Builder, SelfReqOrBuilder>(
                  getReq(),
                  getParentForChildren(),
                  isClean());
          req_ = null;
        }
        return reqBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:RequestBody)
    }

    // @@protoc_insertion_point(class_scope:RequestBody)
    private static final request.RequestBody DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new request.RequestBody();
    }

    public static request.RequestBody getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestBody>
        PARSER = new com.google.protobuf.AbstractParser<RequestBody>() {
      public RequestBody parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RequestBody(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestBody> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RequestBody> getParserForType() {
      return PARSER;
    }

    public request.RequestBody getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SelfReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SelfReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 base = 1;</code>
     */
    int getBase();

    /**
     * <code>int32 exp = 2;</code>
     */
    int getExp();
  }
  /**
   * Protobuf type {@code SelfReq}
   */
  public  static final class SelfReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SelfReq)
      SelfReqOrBuilder {
    // Use SelfReq.newBuilder() to construct.
    private SelfReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SelfReq() {
      base_ = 0;
      exp_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SelfReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              base_ = input.readInt32();
              break;
            }
            case 16: {

              exp_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return request.internal_static_SelfReq_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return request.internal_static_SelfReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              request.SelfReq.class, request.SelfReq.Builder.class);
    }

    public static final int BASE_FIELD_NUMBER = 1;
    private int base_;
    /**
     * <code>int32 base = 1;</code>
     */
    public int getBase() {
      return base_;
    }

    public static final int EXP_FIELD_NUMBER = 2;
    private int exp_;
    /**
     * <code>int32 exp = 2;</code>
     */
    public int getExp() {
      return exp_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (base_ != 0) {
        output.writeInt32(1, base_);
      }
      if (exp_ != 0) {
        output.writeInt32(2, exp_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (base_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, base_);
      }
      if (exp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, exp_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof request.SelfReq)) {
        return super.equals(obj);
      }
      request.SelfReq other = (request.SelfReq) obj;

      boolean result = true;
      result = result && (getBase()
          == other.getBase());
      result = result && (getExp()
          == other.getExp());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BASE_FIELD_NUMBER;
      hash = (53 * hash) + getBase();
      hash = (37 * hash) + EXP_FIELD_NUMBER;
      hash = (53 * hash) + getExp();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static request.SelfReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static request.SelfReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static request.SelfReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static request.SelfReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static request.SelfReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static request.SelfReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static request.SelfReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static request.SelfReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static request.SelfReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static request.SelfReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static request.SelfReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static request.SelfReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(request.SelfReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SelfReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SelfReq)
        request.SelfReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return request.internal_static_SelfReq_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return request.internal_static_SelfReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                request.SelfReq.class, request.SelfReq.Builder.class);
      }

      // Construct using com.sdp.protoEntity.request.SelfReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        base_ = 0;

        exp_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return request.internal_static_SelfReq_descriptor;
      }

      public request.SelfReq getDefaultInstanceForType() {
        return request.SelfReq.getDefaultInstance();
      }

      public request.SelfReq build() {
        request.SelfReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public request.SelfReq buildPartial() {
        request.SelfReq result = new request.SelfReq(this);
        result.base_ = base_;
        result.exp_ = exp_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof request.SelfReq) {
          return mergeFrom((request.SelfReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(request.SelfReq other) {
        if (other == request.SelfReq.getDefaultInstance()) return this;
        if (other.getBase() != 0) {
          setBase(other.getBase());
        }
        if (other.getExp() != 0) {
          setExp(other.getExp());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        request.SelfReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (request.SelfReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int base_ ;
      /**
       * <code>int32 base = 1;</code>
       */
      public int getBase() {
        return base_;
      }
      /**
       * <code>int32 base = 1;</code>
       */
      public Builder setBase(int value) {

        base_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 base = 1;</code>
       */
      public Builder clearBase() {

        base_ = 0;
        onChanged();
        return this;
      }

      private int exp_ ;
      /**
       * <code>int32 exp = 2;</code>
       */
      public int getExp() {
        return exp_;
      }
      /**
       * <code>int32 exp = 2;</code>
       */
      public Builder setExp(int value) {

        exp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 exp = 2;</code>
       */
      public Builder clearExp() {

        exp_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:SelfReq)
    }

    // @@protoc_insertion_point(class_scope:SelfReq)
    private static final request.SelfReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new request.SelfReq();
    }

    public static request.SelfReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SelfReq>
        PARSER = new com.google.protobuf.AbstractParser<SelfReq>() {
      public SelfReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SelfReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SelfReq> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SelfReq> getParserForType() {
      return PARSER;
    }

    public request.SelfReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestBody_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestBody_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SelfReq_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SelfReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021RequestBody.proto\"E\n\013RequestBody\022\021\n\tre" +
      "questId\030\001 \001(\t\022\014\n\004type\030\002 \001(\t\022\025\n\003req\030\003 \001(\013" +
      "2\010.SelfReq\"$\n\007SelfReq\022\014\n\004base\030\001 \001(\005\022\013\n\003e" +
      "xp\030\002 \001(\005B\036\n\023com.sdp.protoEntityB\007request" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RequestBody_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestBody_descriptor,
        new String[] { "RequestId", "Type", "Req", });
    internal_static_SelfReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SelfReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SelfReq_descriptor,
        new String[] { "Base", "Exp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
