// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResponseBody.proto

package com.sdp.self_rpc_done.protoEntity;

public final class response {
  private response() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResponseBodyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResponseBody)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string requestId = 1;</code>
     */
    String getRequestId();
    /**
     * <code>string requestId = 1;</code>
     */
    com.google.protobuf.ByteString
        getRequestIdBytes();

    /**
     * <code>string type = 2;</code>
     */
    String getType();
    /**
     * <code>string type = 2;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>.SelfRsp req = 3;</code>
     */
    boolean hasReq();
    /**
     * <code>.SelfRsp req = 3;</code>
     */
    response.SelfRsp getReq();
    /**
     * <code>.SelfRsp req = 3;</code>
     */
    response.SelfRspOrBuilder getReqOrBuilder();
  }
  /**
   * Protobuf type {@code ResponseBody}
   */
  public  static final class ResponseBody extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ResponseBody)
      ResponseBodyOrBuilder {
    // Use ResponseBody.newBuilder() to construct.
    private ResponseBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseBody() {
      requestId_ = "";
      type_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ResponseBody(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              requestId_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 26: {
              response.SelfRsp.Builder subBuilder = null;
              if (req_ != null) {
                subBuilder = req_.toBuilder();
              }
              req_ = input.readMessage(response.SelfRsp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(req_);
                req_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return response.internal_static_ResponseBody_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return response.internal_static_ResponseBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              response.ResponseBody.class, response.ResponseBody.Builder.class);
    }

    public static final int REQUESTID_FIELD_NUMBER = 1;
    private volatile Object requestId_;
    /**
     * <code>string requestId = 1;</code>
     */
    public String getRequestId() {
      Object ref = requestId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      }
    }
    /**
     * <code>string requestId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      Object ref = requestId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private volatile Object type_;
    /**
     * <code>string type = 2;</code>
     */
    public String getType() {
      Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQ_FIELD_NUMBER = 3;
    private response.SelfRsp req_;
    /**
     * <code>.SelfRsp req = 3;</code>
     */
    public boolean hasReq() {
      return req_ != null;
    }
    /**
     * <code>.SelfRsp req = 3;</code>
     */
    public response.SelfRsp getReq() {
      return req_ == null ? response.SelfRsp.getDefaultInstance() : req_;
    }
    /**
     * <code>.SelfRsp req = 3;</code>
     */
    public response.SelfRspOrBuilder getReqOrBuilder() {
      return getReq();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRequestIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestId_);
      }
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
      }
      if (req_ != null) {
        output.writeMessage(3, getReq());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRequestIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestId_);
      }
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
      }
      if (req_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getReq());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof response.ResponseBody)) {
        return super.equals(obj);
      }
      response.ResponseBody other = (response.ResponseBody) obj;

      boolean result = true;
      result = result && getRequestId()
          .equals(other.getRequestId());
      result = result && getType()
          .equals(other.getType());
      result = result && (hasReq() == other.hasReq());
      if (hasReq()) {
        result = result && getReq()
            .equals(other.getReq());
      }
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestId().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      if (hasReq()) {
        hash = (37 * hash) + REQ_FIELD_NUMBER;
        hash = (53 * hash) + getReq().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static response.ResponseBody parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static response.ResponseBody parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static response.ResponseBody parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static response.ResponseBody parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static response.ResponseBody parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static response.ResponseBody parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static response.ResponseBody parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static response.ResponseBody parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static response.ResponseBody parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static response.ResponseBody parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static response.ResponseBody parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static response.ResponseBody parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(response.ResponseBody prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResponseBody}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResponseBody)
        response.ResponseBodyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return response.internal_static_ResponseBody_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return response.internal_static_ResponseBody_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                response.ResponseBody.class, response.ResponseBody.Builder.class);
      }

      // Construct using com.sdp.protoEntity.response.ResponseBody.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        requestId_ = "";

        type_ = "";

        if (reqBuilder_ == null) {
          req_ = null;
        } else {
          req_ = null;
          reqBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return response.internal_static_ResponseBody_descriptor;
      }

      public response.ResponseBody getDefaultInstanceForType() {
        return response.ResponseBody.getDefaultInstance();
      }

      public response.ResponseBody build() {
        response.ResponseBody result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public response.ResponseBody buildPartial() {
        response.ResponseBody result = new response.ResponseBody(this);
        result.requestId_ = requestId_;
        result.type_ = type_;
        if (reqBuilder_ == null) {
          result.req_ = req_;
        } else {
          result.req_ = reqBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof response.ResponseBody) {
          return mergeFrom((response.ResponseBody)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(response.ResponseBody other) {
        if (other == response.ResponseBody.getDefaultInstance()) return this;
        if (!other.getRequestId().isEmpty()) {
          requestId_ = other.requestId_;
          onChanged();
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (other.hasReq()) {
          mergeReq(other.getReq());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        response.ResponseBody parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (response.ResponseBody) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object requestId_ = "";
      /**
       * <code>string requestId = 1;</code>
       */
      public String getRequestId() {
        Object ref = requestId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          requestId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string requestId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRequestIdBytes() {
        Object ref = requestId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          requestId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string requestId = 1;</code>
       */
      public Builder setRequestId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string requestId = 1;</code>
       */
      public Builder clearRequestId() {

        requestId_ = getDefaultInstance().getRequestId();
        onChanged();
        return this;
      }
      /**
       * <code>string requestId = 1;</code>
       */
      public Builder setRequestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        requestId_ = value;
        onChanged();
        return this;
      }

      private Object type_ = "";
      /**
       * <code>string type = 2;</code>
       */
      public String getType() {
        Object ref = type_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 2;</code>
       */
      public Builder setType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 2;</code>
       */
      public Builder clearType() {

        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>string type = 2;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        type_ = value;
        onChanged();
        return this;
      }

      private response.SelfRsp req_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          SelfRsp, SelfRsp.Builder, SelfRspOrBuilder> reqBuilder_;
      /**
       * <code>.SelfRsp req = 3;</code>
       */
      public boolean hasReq() {
        return reqBuilder_ != null || req_ != null;
      }
      /**
       * <code>.SelfRsp req = 3;</code>
       */
      public response.SelfRsp getReq() {
        if (reqBuilder_ == null) {
          return req_ == null ? response.SelfRsp.getDefaultInstance() : req_;
        } else {
          return reqBuilder_.getMessage();
        }
      }
      /**
       * <code>.SelfRsp req = 3;</code>
       */
      public Builder setReq(response.SelfRsp value) {
        if (reqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          req_ = value;
          onChanged();
        } else {
          reqBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.SelfRsp req = 3;</code>
       */
      public Builder setReq(
          response.SelfRsp.Builder builderForValue) {
        if (reqBuilder_ == null) {
          req_ = builderForValue.build();
          onChanged();
        } else {
          reqBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.SelfRsp req = 3;</code>
       */
      public Builder mergeReq(response.SelfRsp value) {
        if (reqBuilder_ == null) {
          if (req_ != null) {
            req_ =
              response.SelfRsp.newBuilder(req_).mergeFrom(value).buildPartial();
          } else {
            req_ = value;
          }
          onChanged();
        } else {
          reqBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.SelfRsp req = 3;</code>
       */
      public Builder clearReq() {
        if (reqBuilder_ == null) {
          req_ = null;
          onChanged();
        } else {
          req_ = null;
          reqBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.SelfRsp req = 3;</code>
       */
      public response.SelfRsp.Builder getReqBuilder() {

        onChanged();
        return getReqFieldBuilder().getBuilder();
      }
      /**
       * <code>.SelfRsp req = 3;</code>
       */
      public response.SelfRspOrBuilder getReqOrBuilder() {
        if (reqBuilder_ != null) {
          return reqBuilder_.getMessageOrBuilder();
        } else {
          return req_ == null ?
              response.SelfRsp.getDefaultInstance() : req_;
        }
      }
      /**
       * <code>.SelfRsp req = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          SelfRsp, SelfRsp.Builder, SelfRspOrBuilder>
          getReqFieldBuilder() {
        if (reqBuilder_ == null) {
          reqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              SelfRsp, SelfRsp.Builder, SelfRspOrBuilder>(
                  getReq(),
                  getParentForChildren(),
                  isClean());
          req_ = null;
        }
        return reqBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ResponseBody)
    }

    // @@protoc_insertion_point(class_scope:ResponseBody)
    private static final response.ResponseBody DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new response.ResponseBody();
    }

    public static response.ResponseBody getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseBody>
        PARSER = new com.google.protobuf.AbstractParser<ResponseBody>() {
      public ResponseBody parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ResponseBody(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseBody> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ResponseBody> getParserForType() {
      return PARSER;
    }

    public response.ResponseBody getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SelfRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SelfRsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 value = 1;</code>
     */
    long getValue();

    /**
     * <code>int64 costInNanos = 2;</code>
     */
    long getCostInNanos();
  }
  /**
   * Protobuf type {@code SelfRsp}
   */
  public  static final class SelfRsp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SelfRsp)
      SelfRspOrBuilder {
    // Use SelfRsp.newBuilder() to construct.
    private SelfRsp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SelfRsp() {
      value_ = 0L;
      costInNanos_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SelfRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              value_ = input.readInt64();
              break;
            }
            case 16: {

              costInNanos_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return response.internal_static_SelfRsp_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return response.internal_static_SelfRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              response.SelfRsp.class, response.SelfRsp.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private long value_;
    /**
     * <code>int64 value = 1;</code>
     */
    public long getValue() {
      return value_;
    }

    public static final int COSTINNANOS_FIELD_NUMBER = 2;
    private long costInNanos_;
    /**
     * <code>int64 costInNanos = 2;</code>
     */
    public long getCostInNanos() {
      return costInNanos_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (value_ != 0L) {
        output.writeInt64(1, value_);
      }
      if (costInNanos_ != 0L) {
        output.writeInt64(2, costInNanos_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (value_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, value_);
      }
      if (costInNanos_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, costInNanos_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof response.SelfRsp)) {
        return super.equals(obj);
      }
      response.SelfRsp other = (response.SelfRsp) obj;

      boolean result = true;
      result = result && (getValue()
          == other.getValue());
      result = result && (getCostInNanos()
          == other.getCostInNanos());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getValue());
      hash = (37 * hash) + COSTINNANOS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCostInNanos());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static response.SelfRsp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static response.SelfRsp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static response.SelfRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static response.SelfRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static response.SelfRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static response.SelfRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static response.SelfRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static response.SelfRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static response.SelfRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static response.SelfRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static response.SelfRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static response.SelfRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(response.SelfRsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SelfRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SelfRsp)
        response.SelfRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return response.internal_static_SelfRsp_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return response.internal_static_SelfRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                response.SelfRsp.class, response.SelfRsp.Builder.class);
      }

      // Construct using com.sdp.protoEntity.response.SelfRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        value_ = 0L;

        costInNanos_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return response.internal_static_SelfRsp_descriptor;
      }

      public response.SelfRsp getDefaultInstanceForType() {
        return response.SelfRsp.getDefaultInstance();
      }

      public response.SelfRsp build() {
        response.SelfRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public response.SelfRsp buildPartial() {
        response.SelfRsp result = new response.SelfRsp(this);
        result.value_ = value_;
        result.costInNanos_ = costInNanos_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof response.SelfRsp) {
          return mergeFrom((response.SelfRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(response.SelfRsp other) {
        if (other == response.SelfRsp.getDefaultInstance()) return this;
        if (other.getValue() != 0L) {
          setValue(other.getValue());
        }
        if (other.getCostInNanos() != 0L) {
          setCostInNanos(other.getCostInNanos());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        response.SelfRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (response.SelfRsp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long value_ ;
      /**
       * <code>int64 value = 1;</code>
       */
      public long getValue() {
        return value_;
      }
      /**
       * <code>int64 value = 1;</code>
       */
      public Builder setValue(long value) {

        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 value = 1;</code>
       */
      public Builder clearValue() {

        value_ = 0L;
        onChanged();
        return this;
      }

      private long costInNanos_ ;
      /**
       * <code>int64 costInNanos = 2;</code>
       */
      public long getCostInNanos() {
        return costInNanos_;
      }
      /**
       * <code>int64 costInNanos = 2;</code>
       */
      public Builder setCostInNanos(long value) {

        costInNanos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 costInNanos = 2;</code>
       */
      public Builder clearCostInNanos() {

        costInNanos_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:SelfRsp)
    }

    // @@protoc_insertion_point(class_scope:SelfRsp)
    private static final response.SelfRsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new response.SelfRsp();
    }

    public static response.SelfRsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SelfRsp>
        PARSER = new com.google.protobuf.AbstractParser<SelfRsp>() {
      public SelfRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SelfRsp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SelfRsp> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SelfRsp> getParserForType() {
      return PARSER;
    }

    public response.SelfRsp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseBody_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseBody_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SelfRsp_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SelfRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022ResponseBody.proto\"F\n\014ResponseBody\022\021\n\t" +
      "requestId\030\001 \001(\t\022\014\n\004type\030\002 \001(\t\022\025\n\003req\030\003 \001" +
      "(\0132\010.SelfRsp\"-\n\007SelfRsp\022\r\n\005value\030\001 \001(\003\022\023" +
      "\n\013costInNanos\030\002 \001(\003B\037\n\023com.sdp.protoEnti" +
      "tyB\010responseb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ResponseBody_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ResponseBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseBody_descriptor,
        new String[] { "RequestId", "Type", "Req", });
    internal_static_SelfRsp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SelfRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SelfRsp_descriptor,
        new String[] { "Value", "CostInNanos", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
